# SOPS Configuration for NixNAS Secrets
# ======================================
#
# This file configures SOPS (Secrets OPerationS) for encrypting sensitive data.
#
# Setup instructions:
# 1. Generate age key from SSH host key after first boot:
#    ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub
#
# 2. Add the public key below (replace the placeholder)
#
# 3. Optionally add your personal age key for editing secrets:
#    age-keygen -o ~/.config/sops/age/keys.txt
#    cat ~/.config/sops/age/keys.txt | grep "public key"
#
# 4. Edit secrets with: sops secrets/secrets.yaml

keys:
  # NixNAS server key (from SSH host key)
  # Generate after first boot: ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub
  - &nixnas age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # Admin user key (optional, for editing secrets from workstation)
  # Generate: age-keygen -o ~/.config/sops/age/keys.txt
  # - &admin age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

creation_rules:
  # Encrypt all yaml files in secrets/ directory
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *nixnas
          # - *admin  # Uncomment after adding admin key
