# Hardware Configuration
# This file is typically auto-generated by nixos-generate-config
# Customize for your specific hardware

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # =============================================================================
  # BOOT CONFIGURATION
  # =============================================================================

  # Kernel modules needed for boot
  boot.initrd.availableKernelModules = [
    "xhci_pci"      # USB 3.0
    "ahci"          # SATA
    "usbhid"        # USB keyboard/mouse
    "usb_storage"   # USB drives
    "sd_mod"        # SCSI disks
    "nvme"          # NVMe drives
  ];

  boot.kernelModules = [ "kvm-intel" ];  # or kvm-amd for AMD CPUs

  # =============================================================================
  # FILESYSTEM CONFIGURATION
  # =============================================================================

  # USB Boot Drive
  # Update these UUIDs after formatting your USB drive
  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS";
    fsType = "ext4";
    options = [ "noatime" "discard" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
  };

  # ZFS datasets are mounted automatically via zfs.nix

  # Swap (optional - can use zram instead)
  # swapDevices = [ ];

  # Use zram for swap (compressed RAM swap)
  zramSwap = {
    enable = true;
    memoryPercent = 25;  # Use 25% of RAM for zram swap
  };

  # =============================================================================
  # HARDWARE SETTINGS
  # =============================================================================

  # Enable firmware
  hardware.enableRedistributableFirmware = lib.mkDefault true;

  # CPU microcode updates
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Platform (usually auto-detected)
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
